
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/ant0ine/go-json-rest"
  version = "3.3.2"

[[constraint]]
  name = "github.com/ashwanthkumar/slack-go-webhook"
  version = "0.2.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.19"

[[constraint]]
  branch = "master"
  name = "github.com/bww/go-json"

[[constraint]]
  branch = "master"
  name = "github.com/cheungpat/go-json-rest-middleware-jwt"

[[constraint]]
  branch = "master"
  name = "github.com/codeamp/logger"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/extemporalgenome/slug"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-bongo/bongo"
  version = "0.10.4"

[[constraint]]
  branch = "master"
  name = "github.com/google/shlex"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jarcoal/httpmock"

[[constraint]]
  branch = "master"
  name = "github.com/jrallison/go-workers"

[[constraint]]
  branch = "master"
  name = "github.com/lestrrat/go-jwx"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "1.3.1"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"
