apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: codeflow
  name: codeflow
  namespace: development-checkr-codeflow
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: codeflow
        name: codeflow
    spec:
      imagePullSecrets:
      - name: docker-io
      volumes:
      - name: codeflow-config
        configMap:
          name: codeflow-config
      - hostPath:
          path: /var/run/docker.sock
        name: dockersocket
      containers:
      - name: migrate
        args:
        - /bin/sh
        - -c
        - 'cd server/ && go run main.go --config /etc/codeflow/codeflow.yml migrate up && while /bin/true; do sleep 5; done'
        #- 'cd server/ && go run main.go --config /etc/codeflow/codeflow.yml migrate up'
        volumeMounts:
        - mountPath: /etc/codeflow
          name: codeflow-config
        image: docker.io/checkr/checkr-codeflow:latest
      - name: dashboard
        args:
        - node 
        - dashboard/server.js
        image: docker.io/checkr/checkr-codeflow:latest
        ports:
        - containerPort: 4000
          protocol: TCP
          name: dashboard-port
        envFrom:
        - configMapRef:
            name: react-config
        volumeMounts:
        - mountPath: /etc/codeflow
          name: codeflow-config
      - name: api
        args:
        - /go/bin/codeflow
        - --config
        - /etc/codeflow/codeflow.yml
        - server
        - --run=git_sync,kubedeploy,heartbeat,docker_build,slack,route53,webhooks,codeflow,websockets
        image: docker.io/checkr/checkr-codeflow:latest
        volumeMounts:
        - mountPath: /etc/codeflow
          name: codeflow-config
        - mountPath: /var/run/docker.sock
          name: dockersocket
        ports:
        - containerPort: 3001
          protocol: TCP
          name: api-port
        - containerPort: 3002
          protocol: TCP
          name: webhooks-port
        - containerPort: 3003
          protocol: TCP
          name: websocket-port
        
