apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: checkr-codeflow-api
  name: checkr-codeflow-api
  namespace: development-checkr-codeflow
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: checkr-codeflow-api
        name: checkr-codeflow-api
    spec:
      imagePullSecrets:
      - name: docker-io
      volumes:
      - name: codeflow-config
        configMap:
          name: codeflow-config
      - hostPath:
          path: /var/run/docker.sock
        name: dockersocket
      containers:
      - name: api
        args:
        - /go/bin/codeflow
        - --config
        - /etc/codeflow/codeflow.dev.yml
        - server
        - --run=git_sync,kubedeploy,heartbeat,docker_build,slack,route53,webhooks,codeflow,websockets
        image: docker.io/checkr/checkr-codeflow:latest
        volumeMounts:
        - mountPath: /etc/codeflow
          name: codeflow-config
        - mountPath: /var/run/docker.sock
          name: dockersocket
        ports:
        - containerPort: 3001
          protocol: TCP
          name: api-port
        - containerPort: 3002
          protocol: TCP
          name: webhooks-port
        - containerPort: 3003
          protocol: TCP
          name: websocket-port
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: checkr-codeflow-www
  name: checkr-codeflow-www
  namespace: development-checkr-codeflow
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: checkr-codeflow-www
        name: checkr-codeflow-www
    spec:
      imagePullSecrets:
      - name: docker-io
      volumes:
      - name: codeflow-config
        configMap:
          name: codeflow-config
      containers:
      - name: www
        args:
        - node 
        - dashboard/server.js
        image: docker.io/checkr/checkr-codeflow:latest
        ports:
        - containerPort: 9000
          protocol: TCP
          name: dashboard-port
        envFrom:
        - configMapRef:
            name: react-config
        volumeMounts:
        - mountPath: /etc/codeflow
          name: codeflow-config
