apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: codeflow
  name: codeflow
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: codeflow
        name: codeflow
    spec:
      imagePullSecrets:
      - name: docker-io
      volumes:
      - name: codeflow-kubernetes-secrets
        secret:
          defaultMode: 256
          items:
          - key: ca.pem
            mode: 256
            path: ca.pem
          - key: admin.pem
            mode: 256
            path: admin.pem
          - key: admin-key.pem
            mode: 256
            path: admin-key.pem
          - key: kubeconfig
            mode: 256
            path: kubeconfig
          secretName: codeflow-kubernetes-secrets
      - hostPath:
          path: /var/run/docker.sock
        name: dockersocket
      containers:
      - name: dashboard
        args:
        - node 
        - dashboard/server.js
        env:
        - name: REACT_APP_API_ROOT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: react-app-api-root
        - name: REACT_APP_ROOT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: react-app-root
        - name: REACT_APP_WEBHOOKS_ROOT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: react-app-webhooks-root
        - name: REACT_APP_WS_ROOT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: react-app-ws-root
        - name: REACT_APP_PORT
          value: "4000"
        image: docker.io/checkr/codeflow:latest
        ports:
        - containerPort: 4000
          protocol: TCP
          name: dashboard-port
      - name: migrate
        args:
        - /bin/sh
        - -c
        - 'cd server/ && go run main.go --config ./configs/codeflow.dev.yml migrate up'
        env:
        - name: CF_PLUGINS_CODEFLOW_MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-mongodb-database
        - name: CF_PLUGINS_CODEFLOW_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-mongodb-uri
        - name: CF_PLUGINS_CODEFLOW_MONGODB_SSL
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-mongodb-ssl
        image: docker.io/checkr/codeflow:latest
      - name: api
        args:
        - /go/bin/codeflow
        - --config
        - /etc/codeflow.yml
        - server
        - --run=codeflow,webhooks,kubedeploy,websockets,docker_build
        env:
        - name: REACT_APP_API_ROOT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: react-app-api-root
        - name: REACT_APP_ROOT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: react-app-root
        - name: REACT_APP_WEBHOOKS_ROOT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: react-app-webhooks-root
        - name: REACT_APP_WS_ROOT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: react-app-ws-root
        - name: CF_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-environment
        - name: CF_REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-redis-username
        - name: CF_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-redis-password
        - name: CF_REDIS_SERVER
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-redis-server
        - name: CF_REDIS_DATABASE
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-redis-database
        - name: CF_REDIS_POOL
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-redis-pool
        - name: CF_REDIS_PROCESS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-redis-process
        - name: CF_PLUGINS_WEBHOOKS_WORKERS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-webhooks-workers
        - name: CF_PLUGINS_WEBHOOKS_SERVICE_ADDRESS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-webhooks-service-address
        - name: CF_PLUGINS_WEBHOOKS_GITHUB_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-webhooks-github-path
        - name: CF_PLUGINS_CODEFLOW_WORKERS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-workers
        - name: CF_PLUGINS_CODEFLOW_DASHBOARD_URL
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-dashboard-url
        - name: CF_PLUGINS_CODEFLOW_LOGS_URL
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-logs-url
        - name: CF_PLUGINS_CODEFLOW_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-jwt-secret-key
        - name: CF_PLUGINS_CODEFLOW_ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-allowed-origins
        - name: CF_PLUGINS_CODEFLOW_DEFAULT_SERVICE_SPEC_CPU
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-default-service-spec-cpu
        - name: CF_PLUGINS_CODEFLOW_DEFAULT_SERVICE_SPEC_CPU_BURST
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-default-service-spec-cpu-burst
        - name: CF_PLUGINS_CODEFLOW_DEFAULT_SERVICE_SPEC_MEMORY
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-default-service-spec-memory
        - name: CF_PLUGINS_CODEFLOW_DEFAULT_SERVICE_SPEC_MEMORY_BURST
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-default-service-spec-memory-burst
        - name: CF_PLUGINS_CODEFLOW_DEFAULT_SERVICE_SPEC_TERMINATION_GRACE_PERIOD_SECONDS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-default-service-spec-termination-grace-period-seconds
        - name: CF_PLUGINS_CODEFLOW_MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-mongodb-database
        - name: CF_PLUGINS_CODEFLOW_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-mongodb-uri
        - name: CF_PLUGINS_CODEFLOW_MONGODB_SSL
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-mongodb-ssl
        - name: CF_PLUGINS_CODEFLOW_SERVICE_ADDRESS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-service-address
        - name: CF_PLUGINS_CODEFLOW_BUILDS_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-builds-path
        - name: CF_PLUGINS_CODEFLOW_PROJECTS_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-projects-path
        - name: CF_PLUGINS_CODEFLOW_AUTH_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-auth-path
        - name: CF_PLUGINS_CODEFLOW_AUTH_HANDLER
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-auth-handler
        - name: CF_PLUGINS_CODEFLOW_AUTH_OKTA_ORG
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-auth-okta-org
        - name: CF_PLUGINS_CODEFLOW_USERS_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-users-path
        - name: CF_PLUGINS_CODEFLOW_FEATURES_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-features-path
        - name: CF_PLUGINS_CODEFLOW_WEBSOCKETS_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-websockets-path
        - name: CF_PLUGINS_CODEFLOW_BOOKMARKS_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-bookmarks-path
        - name: CF_PLUGINS_CODEFLOW_STATS_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-codeflow-stats-path
        - name: CF_PLUGINS_DOCKER_BUILD_WORKERS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-docker-build-workers
        - name: CF_PLUGINS_DOCKER_BUILD_REGISTRY_HOST
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-docker-build-registry-host
        - name: CF_PLUGINS_DOCKER_BUILD_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-docker-build-registry-username
        - name: CF_PLUGINS_DOCKER_BUILD_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-docker-build-registry-password
        - name: CF_PLUGINS_DOCKER_BUILD_REGISTRY_USER_EMAIL
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-docker-build-registry-user-email
        - name: CF_PLUGINS_DOCKER_BUILD_BUILD_PATH
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-docker-build-build-path
        - name: CF_PLUGINS_DOCKER_BUILD_DOCKER_HOST
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-docker-build-docker-host
        - name: CF_PLUGINS_KUBEDEPLOY_WORKERS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-kubedeploy-workers
        - name: CF_PLUGINS_KUBEDEPLOY_KUBECONFIG
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-kubedeploy-kubeconfig
        - name: CF_PLUGINS_KUBEDEPLOY_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-kubedeploy-environment
        - name: CF_PLUGINS_KUBEDEPLOY_SSL_CERT_ARN
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-kubedeploy-ssl-cert-arn
        - name: CF_PLUGINS_KUBEDEPLOY_NODE_SELECTOR
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-kubedeploy-node-selector
        - name: CF_PLUGINS_KUBEDEPLOY_ACCESS_LOG_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-kubedeploy-access-log-s3-bucket
        - name: CF_PLUGINS_WEBSOCKETS_WORKERS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-websockets-workers
        - name: CF_PLUGINS_WEBSOCKETS_SERVICE_ADDRESS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-websockets-service-address
        - name: CF_PLUGINS_SLACK_WORKERS
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-slack-workers
        - name: CF_PLUGINS_SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: codeflow-config
              key: cf-plugins-slack-webhook-url
        image: docker.io/checkr/codeflow:latest
        ports:
        - containerPort: 3001
          protocol: TCP
          name: api-port
        - containerPort: 3002
          protocol: TCP
          name: webhooks-port
        - containerPort: 3003
          protocol: TCP
          name: websocket-port
        volumeMounts:
        - mountPath: /etc/secrets
          name: codeflow-kubernetes-secrets
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: dockersocket
  