apiVersion: v1
kind: Service
metadata:
  namespace: development-checkr-codeflow
  name: codeflow-api
  labels:
    app: codeflow-api
  annotations:
    # Common AWS Load Balancer Options
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "300"
    ## Cross Zone Load balancing (uncomment to enable)
    #service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    #
    ## Internal (Private) Load Balancer (uncomment to enable)
    # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    #
    ## Enable SSL, set your SSL certificate ARN here
    ## Note, if you enable this you will want to setup a DNS CNAME pointing at ELB.
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:....
    #
spec:
  # To use a different type of service, modify for your needs.
  type: LoadBalancer
  ports:
  - name: api-port
    port: 3001
    protocol: TCP
  - name: webhooks-port
    port: 3002
    protocol: TCP
  - name: websockets-port
    port: 3003
    protocol: TCP
  selector:
    app: checkr-codeflow-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: development-checkr-codeflow
  name: codeflow-dashboard
  labels:
    app: codeflow-dashboard
  annotations:
    # Common AWS Load Balancer Options
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "300"
    ## Cross Zone Load balancing (uncomment to enable)
    #service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    #
    ## Internal (Private) Load Balancer (uncomment to enable)
    # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    #
    ## Enable SSL, set your SSL certificate ARN here
    ## Note, if you enable this you will want to setup a DNS CNAME pointing at ELB.
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:....
    #
spec:
  # To use a different type of service, modify for your needs.
  type: LoadBalancer
  ports:
  - name: dashboard-port
    # Use 443 here if you enabled SSL certificate above.
    port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: checkr-codeflow-www
