apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: mongodb 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        name: mongodb
    spec:
      volumes:
      - name: mongodb-data01
        emptyDir: {}
      containers:
      - name: mongodb-server 
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data01
          mountPath: /data/db