apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keep-mongo
  namespace: development-checkr-codeflow
  labels:
    name: mongo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        name: mongo
    spec:
      volumes:
      - name: mongodb-data01
        emptyDir: {}
      containers:
      - name: mongodb-server 
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data01
          mountPath: /data/db
