apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: development-checkr-codeflow
  labels:
    app: mongo
    databaseVendor: mongodb
spec:
  ports:
  - name: mongo-port
    port: 27017
    protocol: TCP
  selector:
    app: mongo
