apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    databaseVendor: mongodb
spec:
  ports:
  - name: mongo-port
    port: 27017
    protocol: TCP
  selector:
    app: mongodb